name: Playwright Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'  # Stable supported version for Playwright

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt || pip install pytest pytest-playwright playwright
          playwright install --with-deps

      - name: Run Playwright tests
        run: |
          pytest -v --tracing=retain-on-failure

      - name: Upload Playwright trace files (if any)
        if: always()  # ensures it uploads even on test failure
        uses: actions/upload-artifact@v4
        with:
          name: playwright-traces
          path: test-results/  # adjust if you save traces elsewhere
